### ISSUE TITLE
用插件将issues内容转换成博客的内容

### ISSUE THREAD

**Issue by losophy** [losophy/losophy.github.io#8]
之前已经用[Hexo+GitHub Pages博客搭建](https://github.com/losophy/losophy.github.io/issues/6)。

`Hexo`默认文章存放于`source`分支，没有评论系统，不过都可以通过插件进行扩展。本文介绍如何将`hexo`的文章与评论存放于`Github Issue`中（`issue`内容为博客内容，`issue`评论为博客评论）。

## 使用github issue存放文章
这种方案主要优点是，可以专心写博客系统，不用关注`Hexo`本身内容。还可以直接使用`GitHub`的图床（已墙），使用GitHub图床非常简单，把图片文件拖到编辑框就行了。

## 安装插件
```shell
npm install hexo-migrator-github-issue --save
```

## 导入文章
```shell
hexo migrate github-issue 你的Github用户名/你存放hexo的仓库名
```

然后生成部署即可。
```shell
hexo g
hexo d
```

## 使用github issue存放评论
首先在`GitHub`上注册新应用，链接：https://github.com/settings/applications/new 。
![p22o24 md](https://user-images.githubusercontent.com/11263320/117932622-27f4f100-b333-11eb-9e6f-27257ce39dc0.png)
参数说明：
```
Application name： # 应用名称，随意losophy.github.io
Homepage URL： # 网站URL，如https://losophy.github.io
Application description # 描述，随意
Authorization callback URL：# 网站URL，https://losophy.github.io
```
点击注册后，页面跳转如下，其中`Client ID`和`Client Secret`在后面的配置中需要用到，到时复制粘贴即可：
![p22o24 md](https://user-images.githubusercontent.com/11263320/117932970-a356a280-b333-11eb-8da1-b0d0cc4c0bdd.png)
最新一版的`NexT`主题已经集成`gitalk`评论系统。
在主题配置文件`next/_config.yml`中更改如下内容：
```
# Gitalk
# For more information: https://gitalk.github.io, https://github.com/gitalk/gitalk
gitalk:
  enable: true
  github_id: losophy # GitHub repo owner
  repo: comments # Repository name to store issues
  client_id: ******************** # GitHub Application Client ID
  client_secret: ********************* # GitHub Application Client Secret
  admin_user: losophy # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN
```
`enable`打开`gitalk`，`github_id`是`github`帐号，`repo`填评论填充的仓库（因为本仓库`issues`用作转化博客内容，所以我另外起了一个仓库专门存评论），`client_id`填上图的`Client ID`，`client_secret`填上图的`Client Secret`，`admin_user`填`github`帐号。

---
[Recuerda siempre que tu propia resolución de triunfar es más importante que cualquier otra cosa.](https://github.com/losophy/losophy.github.io/issues/8)
